# Pi-Hole self-hosted DNS server to get rid of ads
# includes variables for traefik and authentication PIHOLE_PASSWORD

services:
  pihole:
    # adblock lists: https://firebog.net/
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Ukraine
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - DNS1=127.0.0.1
      - DNS2=1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d

    # Traefik config if enabled
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.pihole.entrypoints=web,websecure"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_HOST}`)"
      # HTTP Services
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=letsencrypt"
      - "traefik.http.services.pihole-svc.loadbalancer.server.port=80"