---
- name: Install docker
  hosts: "{{ my_hosts | d([]) }}"
  become: true

  vars:
    docker_repo_key_path: /etc/apt/keyrings/docker.gpg
    docker_repo_key_url: 'https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg'
    docker_repo_deb: 'deb [arch={{ ansible_architecture|lower }} signed-by={{ docker_repo_key_path }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_lsb.codename | lower }} stable'

  tasks:
    - name: Install docker dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: true

    - name: Add docker gpg key
      ansible.builtin.apt_key:
        url: {{ docker_repo_key_url }}
        state: present
        keyring: {{ docker_repo_key_path }}

    - name: Add docker repository
      ansible.builtin.apt_repository:
        filename: docker
        repo: {{ docker_repo_deb }}
        state: present

    - name: Install docker engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-scan-plugin
          - docker-compose-plugin
        update_cache: true